name: al_mehdi_online_school
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
   - family: Roboto
     fonts:
       - asset: assets/fonts/static/Roboto-Black.ttf
       - asset: assets/fonts/static/Roboto-BlackItalic.ttf
       - asset: assets/fonts/static/Roboto-Bold.ttf
       - asset: assets/fonts/static/Roboto-BoldItalic.ttf
       - asset: assets/fonts/static/Roboto-ExtraBold.ttf
       - asset: assets/fonts/static/Roboto-ExtraBoldItalic.ttf
       - asset: assets/fonts/static/Roboto-ExtraLight.ttf
       - asset: assets/fonts/static/Roboto-ExtraLightItalic.ttf
       - asset: assets/fonts/static/Roboto-Italic.ttf
       - asset: assets/fonts/static/Roboto-Light.ttf
       - asset: assets/fonts/static/Roboto-LightItalic.ttf
       - asset: assets/fonts/static/Roboto-Medium.ttf
       - asset: assets/fonts/static/Roboto-MediumItalic.ttf
       - asset: assets/fonts/static/Roboto-Regular.ttf
       - asset: assets/fonts/static/Roboto-SemiBold.ttf
       - asset: assets/fonts/static/Roboto-SemiBoldItalic.ttf
       - asset: assets/fonts/static/Roboto-Thin.ttf
       - asset: assets/fonts/static/Roboto-ThinItalic.ttf